### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by hexWars** [HiDeoo/astro-d2#10]
### Describe the bug

When I generated a.svg, the SVG file was stored in /public/d2/src/content/posts, which should be normal.

Due to the inability to install d2 on the platform where I deployed the website, I set skipGeneration=true.

Subsequently, I uploaded the website, including the SVG files, but the deployment platform reported an error: Failed to get D2 diagram size at '/src/public/d2/posts/a-0.svg'.

Here, the path is obviously incorrect and should be /public/d2/src/content/posts/a-0.svg.

Why didn't I get an error during the local build, but an error occurred on the Zeabur platform?

I had specified the same Node and npm versions as on Windows.

### To Reproduce

1. install astro-d2
2. npm run dev
3. set skipGeneration=true
4. path error

### Expected behavior

success

### How often does this bug happen?

Every time

### System Info

env:
```
Astro                    v4.8.6
Node                     v20.12.2
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         astro-d2-integration
```

**Comment by hexWars** [comment]
Also, should there be a separate article introducing deployment in the documentation?

Thank you for maintaining this great project.

**Comment by HiDeoo** [comment]
Thanks for your report 🙌 

> When I generated a.svg, the SVG file was stored in /public/d2/src/content/posts, which should be normal.

I actually think this one may be the invalid path and I suspect this may be a Windows paths related issue that the plugin may not handle properly.

I do not have access right now to a Windows machine but as soon as I have, I'll try to see if this is correct and provide a fix.

> Also, should there be a separate article introducing deployment in the documentation?

Yes, definitely, this is something on my todo list (the `starlight-obsidian` has the same issue with its similar [`skipGeneration `](https://starlight-obsidian.vercel.app/configuration/#skipgeneration)) but I didn't have time to write it yet.

**Comment by hexWars** [comment]
thanks
