### ISSUE TITLE
Enable Custom Themes

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/astro-d2#12]
### Is your feature request related to a problem?

Right now [Custom Themes](https://d2lang.com/tour/themes#customizing-themes) in d2 are not supported

### Describe the solution you'd like

Add two additional options to the config: `themeOverrides` and `darkThemeOverrides` with the respective keys based off the D2 docs. 

This may require some additional validation if wanted to ensure the child attributes are valid CSS colors. A simple hex validator could be used for this, or just let D2 surface any errors if they exist.

### Additional Context

I'd be willing to look into this if open to adding it.

**Comment by HiDeoo** [comment]
Thanks for the feedback, always appreciated.

So, this may sound like a stupid question, but I've never used custom themes with D2, and I originally saw that when creating the integration, but aren't custom themes something you specify on the diagram level?

**Comment by lorenzolewis** [comment]
You know what, I believe you're right (and that's probably why I kept hitting my head when trying to get them to work 😅). Feel free to close this one then 🫡

**Comment by HiDeoo** [comment]
Thanks for the clarification.

Altho, something to note is that your idea is really great and I think as soon as an equivalent feature lands in D2, I would like for this integration to support it as well.
