### ISSUE TITLE
Output inline SVG

### ISSUE THREAD

**Issue by jarodtaylor** [HiDeoo/astro-d2#18]
### Is your feature request related to a problem?

We are integrating an AI Chatbot on our Starlight site. Using mermaid in starlight allows us to inline the SVG instead of using an `<img>` tag. D2 outputs the SVG file and then renders it using an `<img>`.  Maybe this is just a limitation of D2? 

### Describe the solution you'd like

Would love to have an option to inline the d2 diagram svg instead of using an image.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

By default, D2 outputs files so relying on `<img>` tags to display them is the easiest way to go. However, there are also a few other points that made me specifically choose this approach, e.g. caching as it's very easy to cache these external images that are usually way less often updated than the pages they are displayed on.

> We are integrating an AI Chatbot on our Starlight site.

I am not very familiar with this kind of setup but is there a relationship between the chatbot and the SVGs?

**Comment by jarodtaylor** [comment]
Totally makes sense! 

So, we're integrating a chatbot on our STarlight site. Basically, just built a React component that hits an endpoint our DS team provides us. Whenever we deploy changes on the site, they get those updates and use the docs to build out their model.

You can see the same kind of idea on CRDB's docs: https://www.cockroachlabs.com/docs/

Anyway, I talked with our DS team and they said that the d2 code in the markdown is what's most important. I think the setback using an image tag is not being able to index that because, unlike an inline svg you can't "search" text in an SVG image.
