### ISSUE TITLE
Change layout engine in the markdown

### ISSUE THREAD

**Issue by jarodtaylor** [HiDeoo/astro-d2#19]
### Is your feature request related to a problem?

Not a problem, really, but a nice to have!

### Describe the solution you'd like

I don't even know if this is possible, but it would be great if we could swap layout engines per diagram in the markdown. For instance, there are times when I like a certain diagram better in ELK or TALA, but currently you can only change this (for all) in the plugin config. It would be amazing if you could do it right in the markdown!

maybe I'm just getting greedy :D

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

The [`layout`](https://astro-d2.vercel.app/attributes/#layout) attribute should now be available in the version [`0.5.0`](https://github.com/HiDeoo/astro-d2/releases/tag/v0.5.0) that I just published.
