### ISSUE TITLE
path to image

### ISSUE THREAD

**Issue by JosefJezek** [HiDeoo/astro-d2#21]
### Describe the bug

I have this output in astro config...
```
output: `../sites/test/public/d2`,
```
and build generates this img path...
```
<img alt="Diagram" decoding="async" loading="lazy" src="/sites/test/public/d2/sites/test/src/content/docs/guides/example-0.svg" width="953" height="268">
```
correct path is `/d2/sites/test/src/content/docs/guides/example-0.svg`

### To Reproduce

info above

### Expected behavior

correct img path

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the feedback.

The issue should now be resolved in the version [`0.5.1`]() that I just released. If you have the [Astro `publicDir` option](https://docs.astro.build/en/reference/configuration-reference/#publicdir) set to `../sites/test/public` and the [Astro D2 `output` option](https://astro-d2.vercel.app/configuration/#output) set to `d2` (which is the default), everything should work as expected.
