### ISSUE TITLE
Output image wrapper

### ISSUE THREAD

**Issue by SamuNatsu** [HiDeoo/astro-d2#23]
### Is your feature request related to a problem?

I need to add a `<div>` wrapper with some attributes for each `<img>` generated by AstroD2

### Describe the solution you'd like

Maybe add a new optional attribute like "wrapper=div.xxxx" helps

The wrapper selector can be parsed into a rehype node by package `hast-util-parse-selector`

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

I feel like this use-case may be a bit out of scope for this integration. A similar example could be the same use-case for all images in Markdown files in Astro projects and having such feature in Astro would be out of scope too. I think the way to solve this would be a custom remark/rehype plugin do this transformation.

I'll obviously keep an eye on this and see if there's more demand for a similar feature.
