### ISSUE TITLE
Cannot target sub scenarios

### ISSUE THREAD

**Issue by reednaa** [HiDeoo/astro-d2#24]
### Describe the bug

D2 diagrams with sub scenarios are unable to be targeted by ´target=subA.subAA` where subA is the first level and subAA is the second level.

### To Reproduce

Add:

```d2 target='subA.subAA'
style.fill: transparent
direction: right

a -> b


scenarios: {
  subA: {
    b -> c

    scenarios: {
      subAA: {
        c -> d
      }
    }
  }
}
```

This compiles using `d2 a.d2 --target=secA.secAA`

### Expected behavior

It should produce the same result as using d2 via the console

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report :raised_hands: 

This should now be solved in the version [`0.5.2`](https://github.com/HiDeoo/astro-d2/releases/tag/v0.5.2) that I just published. Note that the [target](https://astro-d2.vercel.app/examples/attributes/target/) should be quoted in your Markdown, e.g. `` ```d2 target="subA.subAA" ``.
