### ISSUE TITLE
astro-d2 does not find d2

### ISSUE THREAD

**Issue by martrapp** [HiDeoo/astro-d2#3]
### Describe the bug

Even so I had `d2` installed, `astro dev` crashes for me on start
![image](https://github.com/HiDeoo/astro-d2/assets/94928215/4cbd4603-b3d6-4f72-8183-b54b6164194c)

### To Reproduce

1. install d2
2. install integration
3. add example on page
````astro
```d2
direction: right
installation -> configuration
```
```` 
4. start astro

### Expected behavior

Show nice diagrams, don't crash ;-)
on my machine, `d2 --version` outputs `v0.6.3`. `astro-d2` should be prepared to accept version strings that start with 'v'.

### How often does this bug happen?

Every time

### System Info

WSL2/Ubuntu

**Comment by HiDeoo** [comment]
Just published [`v0.1.1`](https://github.com/HiDeoo/astro-d2/releases/tag/v0.1.1) with your fix 🎉 Thanks!
