### ISSUE TITLE
why diagrams text is not selectable?

### ISSUE THREAD

**Issue by ahmadkakarr** [HiDeoo/astro-d2#30]
### Is your feature request related to a problem?

the diagrams text on https://d2lang.com/ is selectable and on astro site https://astro-d2.vercel.app/examples/hello-world/ its not .. why ??

### Describe the solution you'd like

Text should be selectable as on official site?? don't you think ?

**Comment by HiDeoo** [comment]
By default, the diagrams are rendered using the `<img>` tag which prevents the text from being selectable.

To make the text selectable, you can use the [`inline` option](https://astro-d2.vercel.app/configuration/#inline) to render the diagrams as inlined SVGs.
