### ISSUE TITLE
Light/Dark theme control

### ISSUE THREAD

**Issue by michaeltoohig** [HiDeoo/astro-d2#5]
### Is your feature request related to a problem?

I would like the color theme to follow my websites light/dark theme setting and not system theme setting.

### Describe the solution you'd like

Some sort of manual override to set the theme to dark/light based on a custom css selector. I see the svg outputs its own css and has a `@media screen and (prefers-color-scheme:dark)` selector so that could be changed perhaps.

### Additional Context

I use tailwind at the moment so for my shiki css I included a `html.dark` selector to override the shiki theme based on my site's color theme.

**Comment by HiDeoo** [comment]
Thanks for your feedback 🙌 

Unfortunately, the CSS code embedded in the SVGs is entirely generated by D2 and not something I have a lot of control over. My guess would be for such a feature to exist, it would have to be implemented in D2 itself through a new option or something similar.

If this was ever implemented, at this point this plugin could add a new configuration option to support it. Until then, I'm going to close this issue but I would be happy to re-open and implement it if such a feature is ever added to D2.
