### ISSUE TITLE
Including `pad` and `sketch` in global config

### ISSUE THREAD

**Issue by michaeltoohig** [HiDeoo/astro-d2#6]
### Is your feature request related to a problem?

I want all of my d2 diagrams on my astro website to be sketches without typing it on all of the diagrams manually.

### Describe the solution you'd like

I would like more of the attributes to be available in the global config so all of my d2 diagrams automatically are sharing the same pad value or they are by default sketch style. I imagine then we would need to add a `noSketch` or similar attribute so sketch could then be turned off for particular diagrams.

### Additional Context

Is there a reason you could not include them in the global config and would you accept a PR on this?

**Comment by HiDeoo** [comment]
> Is there a reason you could not include them in the global config and would you accept a PR on this?

Nothing really specific, I did not have this use-case yet personally and did not think about it. I would be happy to accept a PR for this.

I think to start with, it would make sense to add [`sketch`](https://astro-d2.vercel.app/attributes/#sketch) and [`pad`](https://astro-d2.vercel.app/attributes/#pad) to the global configuration like you suggested.

On the diagram level, a diagram overriding `pad` should work out of the box I think:

````md
```d2 pad=10
````

For `sketch`, I think I would prefer supporting `false` as a value to disable the sketch instead of adding a new attribute (similar to [`darkTheme`](https://astro-d2.vercel.app/attributes/#darktheme)):

````md
```d2 sketch=false
````

**Comment by HiDeoo** [comment]
Thanks for your great contribution, I just published version [`0.2.0`](https://github.com/HiDeoo/astro-d2/releases/tag/v0.2.0) that includes your changes to support this new feature 🎉
