### ISSUE TITLE
Centering SVG

### ISSUE THREAD

**Issue by hexWars** [HiDeoo/astro-d2#9]
### Is your feature request related to a problem?

I didn't see any configuration for centering SVG.

![1714444596058](https://github.com/HiDeoo/astro-d2/assets/61684793/ff2ad293-7137-40a4-80a1-77c2533d50bb)

### Describe the solution you'd like

Should we add a configuration option?

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands: 
 
I'm not sure this is the responsibility of the plugin to handle this case as we could say the same for every images or block in Markdown and Markdown itself does not really care about any positioning.

 As HTML is totally valid in Markdown, an author could for example use the following syntax to center a diagram:

````md
<p align="center">

```d2
grid-columns: 3
Astro
Starlight
Studio {
  style.stroke-dash: 3
}
```

</p>
````

Which would render as:

<img width="759" alt="image" src="https://github.com/HiDeoo/astro-d2/assets/494699/62c46cc1-fc39-4b0d-af3c-c99e1dcafdc4">
